### ISSUE TITLE
Elements do not show up on firefox that showed on Chrome

### ISSUE THREAD

**Issue by vaniyuva** [tabhresh/Edureka_28thJan#1]
Chrome shows Push up notification when we launch edureka  home page.
So wrote command to close it. 
But the same dont show up in firefox...
please assist.

 package module2pkg;

import java.util.List;

import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.firefox.FirefoxDriver;

public class Sel_mod2_assign_edureka_login {

	public static void main(String[] args) throws InterruptedException {
	
		//Chrome launch
		System.setProperty("webdriver.chrome.driver","D:\\\\Vani_selenium\\\\Installation_stuff\\\\ExeFile\\\\chromedriver.exe");
		WebDriver driver = new ChromeDriver();
		driver.manage().window().maximize();
		
/*
		//Firefox launch
			System.setProperty("webdriver.gecko.driver", "D:\\Vani_selenium\\Installation_stuff\\ExeFile\\geckodriver.exe");
			WebDriver driver = new FirefoxDriver();
	    //	driver.manage().window().fullscreen();
*/
		
		driver.get("https://www.edureka.co/");
		Thread.sleep(3000);
		
	    driver.findElement(By.id("wzrk-cancel")).click();      //to close the pop-up
		
		driver.findElement(By.id("search-inp"));    //  using id
/*		
		driver.findElement(By.name("user_v1[query]"));                                  // using name
		driver.findElement(By.className("search_inp collapse giTrackElementHeader"));   // using classname
		driver.findElement(By.cssSelector("#search-inp"));                              // using CSS
		
		driver.findElement(By.xpath("//*[@id='search-inp']"));                          // using Xpath
*/		
		List <WebElement> list = driver.findElements(By.tagName("a"));                 // using tagname
		System.out.println("No of link tag" +list.size());
		
		driver.findElement(By.linkText("Log In")).click();  	// Using Linktext
		Thread.sleep(2000);
		driver.findElement(By.cssSelector("#new_sign_up_mode > div > div > div.modal-header > button")).click();
		Thread.sleep(2000);
		
		
		driver.findElement(By.partialLinkText("Log")).click();  // using partiallink text
		Thread.sleep(2000);	 
		driver.findElement(By.cssSelector("#new_sign_up_mode > div > div > div.modal-header > button")).click();
		driver.close();
		
	}

}

**Comment by AbhreshSugandhi** [comment]
let me check and get back to u

**Comment by AbhreshSugandhi** [comment]
Apologies for the delay!

I have seen your code I feel try it with implementing wait commands and clubbing with if conditions...
Like: hey wait for the element to be present and then click on it and along with this if element is not present then move to further step... Here you can combine smart wait commands along with If conditions.
try it and share that code will check and help u!
