### ISSUE TITLE
FB New user registration on firefox

### ISSUE THREAD

**Issue by ctavish** [tabhresh/Edureka_28thJan#2]
`package Module2Assignment;

import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;

public class Assignment_Firefox {

	public static void main(String[] args) {
		
		
		System.setProperty("webdriver.gecko.driver", "E:\\Selinium\\InstallationStuff\\ExeFiles\\geckodriver.exe");
		WebDriver driver = new FirefoxDriver();
		driver.get("https://www.facebook.com/");
		//driver.manage().window().maximize();
		
		//Click on Create a Page for a celebrity, band or business.
		driver.findElement(By.linkText("Create a Page")).click();
		//Go Back to sign up page
		driver.navigate().back();
		//Click on Forgot Account
		driver.findElement(By.partialLinkText("Forgot")).click();
		//Go Back to sign up page
		driver.navigate().back();
		driver.findElement(By.name("firstname")).sendKeys(("Tavish"));
		driver.findElement(By.id("u_0_l")).sendKeys("Chadha");
		driver.findElement(By.xpath("//*[@name = 'reg_email__']")).sendKeys("tavish.test@gmail.com");
		//driver.findElement(By.id("u_0_r")).sendKeys("tavish.test@gmail.com");
		driver.findElement(By.id("u_0_v")).sendKeys("Selenium@123");
		try {
					Thread.sleep(3000);
				} catch (InterruptedException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
		driver.findElement(By.cssSelector("#day")).click();
		driver.findElement(By.xpath("//*[@id=\"day\"]/option[4]")).click();
		driver.findElement(By.cssSelector("#month")).click();
		driver.findElement(By.xpath("//*[@id=\"month\"]/option[8]")).click();
		driver.findElement(By.cssSelector("#year")).click();
		driver.findElement(By.xpath("//*[@id=\"year\"]/option[36]")).click();
		driver.findElement(By.id("u_0_a")).click();
		driver.findElement(By.name("websubmit")).click();

	}

}
`

**Comment by AbhreshSugandhi** [comment]
its working fine at my end the only thing i felt was you have not written one steps "//enter email id in the re-enter email id text box" which is not allowing to perform the signup click step. Though the signup button gets clicked but nothing happened only it highlighted that you have not filled up the complete form.
